### ISSUE TITLE
Homebrew Cask installations fail on macOS 13 due to missing Cask folder

### ISSUE THREAD

**Issue by marcocebrian** [App-Fair/App#3]
I can't barely install any apps. Always getting this error:

`The operation couldn’t be completed. /private/var/folders/dw/xxxpgm9n56xg6q_0ttkz2mrc0000gn/T/scriptcmd-4C361CD4-B233-4A37-B80F-9C474EBAA853.scpt:0:451: execution error: /Users/eriond/Library/Application\ Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/2.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.4\)\ curl/7.79.1 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/fork.rb
/Users/eriond/Library/Application\ Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/2.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.4\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://cdn.fork.dev/mac/Fork-2.18.1.dmg
Error: Download failed on Cask 'fork' with message: No such file or directory @ rb_file_s_symlink - (../downloads/54d1e5efe8841eb3a1bb2d9488bc8d50147313a56ed501241c8b3b6c9ace7d85--Fork-2.18.1.dmg, /Users/eriond/Library/Caches/Homebrew/Cask/fork--2.18.1.dmg)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:363:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:363:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:361:in `ln_s'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/download_strategy.rb:426:in `fetch'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/installer.rb:180:in `download'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/installer.rb:75:in `fetch'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/installer.rb:106:in `install'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `block in install_casks'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/cmd/install.rb:77:in `each'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/cmd/install.rb:77:in `install_casks'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cmd/install.rb:179:in `install'
/Users/eriond/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>' (1)
`

**Comment by marcocebrian** [comment]
I have given it permission to access to whole drive. Still same problem with all apps.

**Comment by gerbenhoogendam** [comment]
I have the same problem, home-brew installed, full disk permissions, accessibility in system preferences enabled, still have not been able to install a single app.

**Comment by gerbenhoogendam** [comment]
I had this issue, talked to the developer on Discord and he helped me fix this!
My issue on an M1 Mac running MacOS 13 beta .. I Know😏 was fixed by:
Creating the missing folder: ~/Library/Caches/Homebrew/Cask/ 
The directory touch ~/Library/Caches/Homebrew/ existed, not the Cask folder here. Just created this folder, relaunched AppFair, and all worked great! 

Tnx so much!!!

**Comment by marcprux** [comment]
Interesting to hear that this happens on the macOS 13 beta. I haven't heard any other reports about it on macOS 12 yet.

Once I get set up with the beta I'll try to see if I can reproduce.

**Comment by okyr-ux** [comment]
I have the same issue on macOS 12.6.3
