### ISSUE TITLE
Error running installier

### ISSUE THREAD

**Issue by leon47331** [App-Fair/App#5]
Hello,

I was about to install some apps but every time I get the following error:

`
The operation couldn’t be completed. /private/var/folders/hr/smqh17jj54z_twj4x8b1hb0w0000gn/T/scriptcmd-58EF3EC6-2FC8-47C4-B120-7192D6C363E0/App Fair Command.scpt:0:451: execution error: /Users/Leon/Library/Application\ Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/2.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --fail --silent --max-time 5 --retry 3 --location --remote-time --output /Users/Leon/Library/Caches/Homebrew/api/formula.json --header If-Modified-Since:\ Mon,\ 18\ Jul\ 2022\ 16:46:03\ GMT --compressed --silent https://formulae.brew.sh/api/formula.json
/Users/Leon/Library/Application\ Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/2.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --max-time 5 --retry 3 --fail https://formulae.brew.sh/api/cask-source/xcodes.rb
/Users/Leon/Library/Application\ Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/2.X.Y\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.0.1\)\ curl/7.77.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/RobotsAndPencils/XcodesApp/releases/download/v1.6.0b14/Xcodes.zip
Error: Download failed on Cask 'xcodes' with message: No such file or directory @ rb_file_s_symlink - (../downloads/7992e0306d8ecf041450f93c44cc8295c83f95bcb75f8cf4ae1a869b8caa6506--Xcodes.zip, /Users/Leon/Library/Caches/Homebrew/Cask/xcodes--1.6.0,14.zip)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:363:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:363:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:361:in `ln_s'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/download_strategy.rb:426:in `fetch'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/installer.rb:185:in `download'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/installer.rb:75:in `fetch'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/installer.rb:106:in `install'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/cmd/install.rb:183:in `install'
/Users/Leon/Library/Application Support/app.App-Fair/appfair-homebrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>' (1)
`

What can I do now?

**Comment by leon47331** [comment]
Ohh nevermind... I solved the issue with #3
